# task to config supervisord programs

- name: add supervisord program config
  template:
    src: program.srv.j2
    dest: /etc/t.supervisor/conf.d/{{ item.key }}.svc
  with_dict: '{{ s_programs }}'

- name: ensure program is present
  supervisorctl:
    name: '{{ item.key }}'
    state: present
    config: /etc/t.supervisor/supervisord.conf
  with_dict: '{{ s_programs }}'

- name: ensure program is started
  supervisorctl:
    name: '{{ item.key }}'
    state: started
    config: /etc/t.supervisor/supervisord.conf
  with_dict: '{{ s_programs }}'
