- name: create corp directory
  file: path=/corp/tmp state=directory

- name: create corp logs directory
  file: path=/corp/log state=directory mode=0777

- name: create owner libs dir
  file: 
    path: /opt/pink_libs
    state: directory
    mode: 0700

- name: config syslog forwarding
  template:
    src: rsyslog-graylog.conf.j2
    dest: /etc/rsyslog.d/00-graylog.conf
  notify:
    - restart rsyslog
